name: 'TCLB Test'
description: 'This action tests TCLB'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  ref:
    description: branch or tag to test
    default: master
runs:
  using: 'composite'
  steps:
    - run: |
        CC=gcc
        CXX=g++
        DIR="TCLB"
        if test -d "$DIR"
        then
          rm -rf "$DIR"
        fi
        git clone --depth 1 --branch "${{ inputs.ref }}" "https://github.com/${{ inputs.repository }}.git" "$DIR"
        cd "$DIR"
        make configure
        ./configure --disable-cuda
        make d2q9
      shell: bash
