name: 'TCLB Test'
description: 'This action tests TCLB'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  ref:
    description: branch or tag to test
    default: master
  aptinstall:
    description: install packages with APT
    default: false
runs:
  using: 'composite'
  steps:
    - run |
        if test "${{ inputs.aptinstall }}" == "true"
        then
          sudo apt-get install nvidia-profiler nvidia-cuda-dev nvidia-cuda-toolkit  \
                       openmpi-bin libopenmpi-dev lcov time r-base-dev r-recommended
        fi
        DIR="TCLB"
        if test -d "$DIR"
        then
          rm -rf "$DIR"
        fi
        git clone --depth 1 --branch "${{ inputs.ref }}" "https://github.com/${{ inputs.repository }}.git" "$DIR"
        cd "$DIR"
        tools/install.sh rdep
        make configure
        ./configure --disable-cuda
        make d2q9
      shell: bash
      id: compile
