name: 'TCLB Test'
description: 'This action tests TCLB'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  ref:
    description: branch or tag to test
    default: master
  install:
    description: install dependencies
    default: false
  configureoptions:
    description: options for configure
    default: --disable-cuda
  model:
    description: model to compile
    default: d2q9
runs:
  using: 'composite'
  steps:
    - run: |
        BRANCH="$(echo "${{ inputs.ref }}" | sed 's|refs/heads/||')"
        REPO="${{ inputs.repository }}"
        DIR="TCLB"
        if test -d "$DIR"
        then
          rm -rf "$DIR"
        fi
        echo "Cloning branch $BRANCH from $REPO into $DIR"
        git clone --depth 1 --branch "$BRANCH" "https://github.com/$REPO.git" "$DIR"
        cd "$DIR"
        if test "${{ inputs.install }}" == "true"
        then
          sudo tools/install.sh r
          sudo tools/install.sh openmpi
          sudo tools/install.sh python-dev
        fi
        tools/install.sh rdep
        make configure
        ./configure ${{ inputs.configureoptions }}
        make "${{ inputs.model }}"
      shell: bash
      id: compile
