name: Testing the test

on:
  push:
    branches: [ master ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: CFD-GO/action_TCLB_test@master
      with:
        repository: CFD-GO/TCLB
        aptinstall: true
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: CFD-GO/action_TCLB_test@master
      with:
        repository: CFD-GO/TCLB
        aptinstall: true
